#!/bin/sh

### BEGIN INIT INFO
# Provides:          drcom
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the dail drcom
# Description:       starts drcom using start-stop-daemon
### END INIT INFO

case $1 in
        start)
                git pull origin master
                ;;
        stop)
                
                ;;
        *)
                echo "Usage: $0 (start|stop)"
                ;;
esac
exit 0